
# **SciKit Learn Closed Linear Regression**


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('/content/CarPrice_Assignment.csv')
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [3]:
features = df[['horsepower', 'highwaympg', 'peakrpm', 'curbweight', 'wheelbase', 'stroke']]

X_train = np.array(features)
y_train = np.array(df['price'])

scaler = StandardScaler()
X_norm = scaler.fit_transform(X_train)

print(X_norm)

[[ 0.17448278 -0.54605874 -0.26296022 -0.01456628 -1.6907718  -1.83937734]
 [ 0.17448278 -0.54605874 -0.26296022 -0.01456628 -1.6907718  -1.83937734]
 [ 1.26453643 -0.69162706 -0.26296022  0.51488192 -0.70859588  0.68594616]
 ...
 [ 0.75753473 -1.12833203  0.78785546  0.87875722  1.72187336 -1.23202105]
 [ 0.04773235 -0.54605874 -0.68328649  1.27343679  1.72187336  0.46218332]
 [ 0.25053303 -0.83719538  0.57769233  0.97502053  1.72187336 -0.33696969]]


In [4]:
linear_model = LinearRegression()
linear_model.fit(X_norm, y_train)

b = linear_model.intercept_
w = linear_model.coef_
print(f"w = {w:}, b = {b:0.2f}")

w = [4001.00009038 1339.1963389   251.80205332 4265.63156114  772.80873584
 -459.17097085], b = 13276.71


In [8]:
X_predict = [[ 0.179, -0.547, -0.223, -0.014, -1.86, -1.34], [ 0.140, -0.546, -0.889, -0.1109, -1.27, -1.83], [ 1.261, 0.6891,  0.2623, 0.5137, -0.70,  0.6999]]

prediction = linear_model.predict(X_predict)
print(f'prediction using scikit-learn linear regression : {prediction}')

prediction using scikit-learn linear regression : [12322.34334205 12267.55459894 20639.7746158 ]
